<a href="https://colab.research.google.com/github/mmundhe625/dspy1/blob/main/exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aim**: Learn basics of Numpy library for storing and efficiently processing any external data into python execution pipeline.

*Theory*: NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. In some ways, NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures. *italicized text*

**Working :**

In [ ]:
import numpy
numpy.__version__

'2.0.2'

**A Python List Is More Than Just a List**

Let's consider now what happens when we use a Python data structure that holds many Python objects. The standard mutable multi-element container in Python is the list. We can create a list of integers as follows:

In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
L = list(range (int(input())))
L

6


[0, 1, 2, 3, 4, 5]

In [ ]:
type(L[0])

int

In [ ]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5']

In [ ]:
type(L2[0])

str

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

**Fixed-Type Arrays in Python**

Python offers several different options for storing data in efficient, fixed-type data buffers. The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Creating Arrays from Python Lists**

First, we can use np.array to create arrays from Python lists:

In [ ]:
import numpy as np
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [ ]:

np.array([1.47, 4, 2, 5, 3])

array([1.47, 4.  , 2.  , 5.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [ ]:
np.array([range(i,i+4) for i in [0, 0, 0]])

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

**Creating Arrays from Scratch**

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((2, 4), dtype=float)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0, 20, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.linspace(0, 3, 4)

array([0., 1., 2., 3.])

In [ ]:
np.random.random((4, 3))


array([[0.46156292, 0.46918145, 0.53344498],
       [0.35211521, 0.82678821, 0.17093831],
       [0.59481377, 0.52548638, 0.07301112],
       [0.97878121, 0.93659206, 0.1838866 ]])

In [ ]:
np.random.normal(0, 6, (3, 3))

array([[-8.90154485,  0.63301724, -4.81929314],
       [-2.20401908, -6.87851597, -8.11467471],
       [-6.13128804, -4.67942303, -3.18835099]])

In [ ]:
np.random.randint(0, 54, (3, 3))

array([[47, 22, 49],
       [ 7,  6, 21],
       [33, 12, 28]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.empty(6)

array([8.23890684e-316, 0.00000000e+000, 5.43370149e-291, 1.25990588e-300,
       1.39067116e-309, 2.68866374e-317])

**NumPy Standard Data Types**

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table. Note that when constructing an array, they can be specified using a string:

np.zeros(10, dtype='int16')
Or using the associated NumPy object:

np.zeros(10, dtype=np.int16)
Following table shows all datatypes for Numpy Array



**NumPy Array Attributes**

We will learn about important Attributes with NumPy Array objects

Each array object has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array), the dtype, the data type of the array :

In [ ]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)


print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


**Array Indexing: Accessing Single Elements**

Next we learn how to access single element in a NumPy array NumPy follows indexing similar to that of Python in a dimension index starts at 0 till length-1

So x1[0] will mean 0th element and x1[5] means sixth element in array x1.

We can use negative index value to indicate accessing elements from back side of array.

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices as shown in below code cell.

In [ ]:
x2[2, 0]

np.int64(1)

In [ ]:
print(x2)
x4=x2[0, 0]

x4

[[10  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


np.int64(10)

In [ ]:
x2[0, 0] = 10
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

**Array Slicing: Accessing Subarrays**

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]
If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

**One-dimensional subarrays**

In [ ]:

x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
import array
import numpy as np
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[4:7]

array([4, 5, 6])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


In [ ]:
x2[:2, :3]

array([[4, 0, 8],
       [7, 0, 8]])

In [ ]:
print(x2[:, 0])

[4 7 1]


In [ ]:
x2

array([[4, 0, 8, 8],
       [7, 0, 8, 0],
       [1, 1, 9, 5]])

In [ ]:
print(x2[0, :])

[4 0 8 8]


In [ ]:
x2_sub = x2[:2, :2]
x2_sub

array([[4, 0],
       [7, 0]])

In [ ]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  0],
       [ 7,  0]])

In [ ]:
x2_sub_copy=x2_sub
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  0]
 [ 7  0]]
[[42  0  8  8]
 [ 7  0  8  0]
 [ 1  1  9  5]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print("\n")
print(lower)


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print("\n")
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)
big_array

2.25 s ± 325 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


array([45, 48, 65, ..., 93, 62, 19])

In [ ]:
%timeit (1.0 / big_array)
big_array

1.78 ms ± 174 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


array([45, 48, 65, ..., 93, 62, 19])

In [ ]:
import numpy as np

x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
#some advanced arithmatic expression   -(x/2+1)^2
-(0.5*x + 1) ** 2

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


array([-1.  , -2.25, -4.  , -6.25])

In [ ]:
from scipy import special
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


Many other special functions like error functions, beta integral can also be evaluated.

**Aggregates**

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object. For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling reduce on the add ufunc returns the sum of all elements in the array:

In [ ]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [ ]:
from scipy import special


# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("\n")
print("ln|gamma(x)| =", special.gammaln(x))
print("\n")
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]


ln|gamma(x)| = [ 0.          3.17805383 12.80182748]


beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [ ]:


x = np.arange(1, 6)
np.add.reduce(x)


np.multiply.reduce(x)


#note the difference in output with accumulate
np.add.accumulate(x)



array([ 1,  3,  6, 10, 15])

**QUESTIONS**

1. What are UFuncs in NumPy?

ANS:-
UFuncs (Universal Functions) are functions in NumPy that operate element-wise on ndarray objects.

They:

Perform fast vectorized operations.

Support broadcasting.

Work on arrays of any dimension.

Are implemented in C for high performance.

2. Which are various attributes of numy arrays object?

ANS:-


| Attribute      | Description                          |
| -------------- | ------------------------------------ |
| `arr.ndim`     | Number of dimensions                 |
| `arr.shape`    | Tuple representing dimensions        |
| `arr.size`     | Total number of elements             |
| `arr.dtype`    | Data type of elements                |
| `arr.itemsize` | Size (in bytes) of each element      |
| `arr.nbytes`   | Total bytes consumed                 |
| `arr.T`        | Transpose of array                   |
| `arr.strides`  | Byte steps to move in each dimension |

3. If you have 3 dimentional array in numpy object Obj how to identify its size, type and dimentions ?

ANS:-
import numpy as np

Obj = np.random.randint(1, 10, (3,4,2))


print("Size:", Obj.size)  
    
print("Shape:", Obj.shape)
     # Dimensions
print("Dimensions:", Obj.ndim)
  
print("Data type:", Obj.dtype)  

4. Consider array object named Obj with dimentions 3*4*2 and you want to convert it to 4*6 shape exlpain how will you do it ? Show this using a code cell, taking an example of 3*4*2 np array of random int between 1 and 50.

ANS:-

Total elements:

3 × 4 × 2 = 24
4 × 6 = 24

Since total elements match, we can reshape.


import numpy as np


Obj = np.random.randint(1, 51, (3,4,2))

print("Original shape:", Obj.shape)


Obj_reshaped = Obj.reshape(4,6)

print("New shape:", Obj_reshaped.shape)
print(Obj_reshaped)


5. Consider above 4*6 array, sample 2*3 sub array from left bottom of this array store the result in varible named subObjCpy.

ANS:-

Assuming we use the reshaped 4×6 array:

Left-bottom means:

Last 2 rows

First 3 columns

subObjCpy = Obj_reshaped[-2:, :3].copy()

print("Sub array:")
print(subObjCpy)

6. Make changes in 1 perticular value in the subObjCpy. Check values of Obj subObjCpy to check impact of this change of element in original and copied object. What do you conclude?

ANS:-

subObjCpy[0,0] = 999

print("Modified subObjCpy:")
print(subObjCpy)

print("Original Obj_reshaped:")
print(Obj_reshaped)

conclusion:

Since we used .copy(), modifying subObjCpy does NOT affect the original array.
If we had NOT used .copy(), changes would reflect in the original array because slicing returns a view, not a copy.

7. If you were to filter sub array view from above Obj object and want to apply modification in original and/or sub obj change respective element in other how will you achieve it?


ANS:-

If you want changes in sub-array to reflect in original:

subObj = Obj_reshaped[-2:, :3]   # This is a view

subObj[0,0] = 555

print(Obj_reshaped)   # Original will change



Slicing (arr[a:b]):Returns view (shares memory)
.copy(): creates an independent copy
.reshape(): returns view when possible

**Conclusion** : Thus we have learned basics of Numpy library for storing and efficiently processing any external data into python execution pipeline.